### ISSUE TITLE
im back 14 year old

### ISSUE THREAD

**Issue by NotLexer9** [Deus-Scissuras/Loophole.Dox.#1]
Yep when I get back in School on September I will put things on my GitHub. Dont worry I will train to be more powerful than you. Just wait for it.

**Comment by NotLexer9** [comment]
![image](https://avatars.githubusercontent.com/u/135243719?s=96&v=4)
<br><h2 title='The future'>NOTLEXER IS BETTER THAN REALHACK</h2>

**Comment by Deus-Scissuras** [comment]
Ok idc

**Comment by NotLexer9** [comment]
Bro must have thought woman would save him .

**Comment by NotLexer9** [comment]
Realhack1 be like: 💩 poop 💩

**Comment by Deus-Scissuras** [comment]
No I just idc I haven't coded in like a month

**Comment by Deus-Scissuras** [comment]
I forgot what happened Who are you again?

**Comment by Deus-Scissuras** [comment]
Lol that code is so simple

**Comment by Deus-Scissuras** [comment]
How can I create a rainbow effect on my text?
<h1>Rainbow</h1>


h1 {
    display:inline-block;
    font-size: 72px;
    /* Here you can change angle of gardient also as 45deg here */
    background: linear-gradient(45deg,#FF0000,#FF7F00,#FFFF00,#00FF00,#0000FF,#4B0082,#8B00FF);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-size:100%;
}


h1 {
    display:inline-block;
    font-size: 72px;
    background: linear-gradient(45deg,#FF0000,#FF7F00,#FFFF00,#00FF00,#0000FF,#4B0082,#8B00FF);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-size: 400% 400%;

    -webkit-animation: rainbowanim 10s ease infinite;
       -moz-animation: rainbowanim 10s ease infinite;
            animation: rainbowanim 10s ease infinite;
}

@-webkit-keyframes rainbowanim {
    0%{background-position:0% 50%}
    50%{background-position:100% 50%}
    100%{background-position:0% 50%}
}
@-moz-keyframes rainbowanim {
    0%{background-position:0% 50%}
    50%{background-position:100% 50%}
    100%{background-position:0% 50%}
}
@keyframes rainbowanim { 
    0%{background-position:0% 50%}
    50%{background-position:100% 50%}
    100%{background-position:0% 50%}
} ayo

**Comment by Deus-Scissuras** [comment]
<div class="animated_rainbow_3">Rainbow Stroke</div>

<style>
.animated_rainbow_3 {
	color: #F00;
	-webkit-text-fill-color: transparent;
	-webkit-background-clip: text;
	font-size: 42px;
	font-family: Arial Black, Gadget, sans-serif;
	-webkit-text-stroke-width: 2px;
	-webkit-text-stroke-color: #FF0000;
	-webkit-animation: animatedBackground_c 2s infinite alternate;
}

@keyframes animatedBackground_c {
	0% {-webkit-text-stroke-color: #ff8b00}
	10% {-webkit-text-stroke-color: #e8ff00}
	20% {-webkit-text-stroke-color: #5dff00}
	30% {-webkit-text-stroke-color: #00ff2e}
	40% {-webkit-text-stroke-color: #00ffb9}
	50% {-webkit-text-stroke-color: #00b9ff}
	60% {-webkit-text-stroke-color: #002eff}
	70% {-webkit-text-stroke-color: #5d00ff}
	80% {-webkit-text-stroke-color: #e800ff}
	90% {-webkit-text-stroke-color: #ff008b}
	100% {-webkit-text-stroke-color: #ff0000}
}

</style>

**Comment by Deus-Scissuras** [comment]
Look one rule don't report each other
At all

**Comment by Deus-Scissuras** [comment]
I start School  in early August I get a month head start not really cause I need to pack in a good grade first then its on

**Comment by NotLexer9** [comment]
https://github.com/Deus-Scissuras/Loophole.Dox./issues/2
ARE U OK BRO

**Comment by NotLexer9** [comment]
@Deus-Scissuras https://github.com/Deus-Scissuras/Loophole.Dox./issues/2 ARE U MAD

**Comment by Deus-Scissuras** [comment]
Bruh wth 💀💀💀

**Comment by NotLexer9** [comment]
@Deus-Scissuras your so damn mad #4

**Comment by Deus-Scissuras** [comment]
I’m single as hell right now but I had more girls then you

**Comment by Deus-Scissuras** [comment]
![image](https://avatars.githubusercontent.com/u/131894406?v=4)
<br><h2 title='This goofy'>Realhack1 is better than Notlever9  (Notlever9 POOP ON HIS MOM #2 )</h2>

**Comment by NotLexer9** [comment]
..
