### ISSUE TITLE
Your a girl?

### ISSUE THREAD

**Issue by NotLexer9** [Deus-Scissuras/Loophole.Dox.#13]
then I am boy + I'm smarter than you + you can't code + I am pro + poor you + cryer gril + the girl who falls for men (pls not me)

**Comment by NotLexer9** [comment]
A person named simpo wanted u by his hey baby girl song and ur bf got so jealous he cried and made u kriss simpo cuz ur bf doesn't need u

**Comment by Deus-Scissuras** [comment]
I’m single and I’m better then you Virgin

**Comment by Deus-Scissuras** [comment]
I have All A’a And had 3 A+

**Comment by Deus-Scissuras** [comment]
I’m so Confused

**Comment by Deus-Scissuras** [comment]
You got discord?

**Comment by NotLexer9** [comment]
Yes I got discord

**Comment by NotLexer9** [comment]
And I am a pro

**Comment by NotLexer9** [comment]
I like make a mod menu for acellus and u never did that

**Comment by NotLexer9** [comment]
Made what mod

**Comment by NotLexer9** [comment]
I made that mod menu first

**Comment by NotLexer9** [comment]
Lol

**Comment by NotLexer9** [comment]
It was the McProgrammerX account I did that

**Comment by Deus-Scissuras** [comment]
I told you I’m making a mod menu that actually works
