### ISSUE TITLE
A note for Deus.

### ISSUE THREAD

**Issue by NotLexer9** [Deus-Scissuras/Loophole.Dox.#15]
Deus I know that you get A's but you do the bad things to get that also im the coolkid here. You won't even beat me in a coding battle cuz your a noob that html trick is just markdown abilities.

If you wanna continue this conversation here is my discord:
@ProgramCoders

**Comment by Deus-Scissuras** [comment]
I added you

**Comment by Deus-Scissuras** [comment]
Bozo blocked me cause I made this kid mad i could block you but I won’t cause it’s funny and I’m not soft

**Comment by NotLexer9** [comment]
Whatever I'm making more funny jokes

**Comment by Deus-Scissuras** [comment]
Unblock me so I can have "private combo"

**Comment by Deus-Scissuras** [comment]
What’s your TikTok and I’m getting a PFP ARMY
