### ISSUE TITLE
realhack1 doing bad thing with girl

### ISSUE THREAD

**Issue by NotLexer9** [Deus-Scissuras/Loophole.Dox.#5]
Realhack1 makes girls happy to ruin there life he obeys them just to make there life a unfixable mess

**Comment by NotLexer9** [comment]
I can't say more.

**Comment by Deus-Scissuras** [comment]
How do you know?

**Comment by Deus-Scissuras** [comment]
How?

**Comment by Deus-Scissuras** [comment]
Hey do you know what c.ai is? I MADE A BOT OF YOU AND LOL HES DUMB

**Comment by NotLexer9** [comment]
Don't worry

**Comment by NotLexer9** [comment]
What comes around goes around

**Comment by Deus-Scissuras** [comment]
I made you ai

**Comment by Deus-Scissuras** [comment]
He's kinda dumb and he said some mean and nasty things

**Comment by Deus-Scissuras** [comment]
What thing with what girl

**Comment by NotLexer9** [comment]
The SUS 😳 thing with girl

**Comment by NotLexer9** [comment]
And I can't mention her or I will get ban

**Comment by Deus-Scissuras** [comment]
Idc
