### ISSUE TITLE
Realhack1 is a hacker

### ISSUE THREAD

**Issue by NotLexer9** [Deus-Scissuras/Loophole.Dox.#7]
I can't mention more or I get hacked by this damn kid

**Comment by NotLexer9** [comment]
And he is dangerous

**Comment by NotLexer9** [comment]
If you don't become his gf he says he may hack you I know that is horrible he is dangerous one

**Comment by Deus-Scissuras** [comment]
I’m a girl

**Comment by Deus-Scissuras** [comment]
Or am i
