### ISSUE TITLE
Realhack1 force girl to give him child

### ISSUE THREAD

**Issue by NotLexer9** [Deus-Scissuras/Loophole.Dox.#9]
Wow wow that's so shocking I think I am going to the hospital cuz I am so shocked at this.

**Comment by Deus-Scissuras** [comment]
Ok 😀😀😀

**Comment by Deus-Scissuras** [comment]
You got a phone?

**Comment by Deus-Scissuras** [comment]
I told you I’m a girl

**Comment by Deus-Scissuras** [comment]
Dawg is a lier

**Comment by Deus-Scissuras** [comment]
@NotLexer9 I’m high as shirtss
